config/routes.rb
Rails.application.routes.draw do
  resources :chords
  get 'welcome/index'

  resources :chords
  resources :songs
  resources :composers
  root 'welcome#index'
  mount Ryakuzu::Engine => '/ryakuzu'
end

app/models/chord.rb
class Chord < ActiveRecord::Base
end

app/models/composer.rb
class Composer < ActiveRecord::Base
end

app/models/k_file.rb
class KFile < ActiveRecord::Base
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :composer
  has_one :midi_file, as: :parent

  enum key: %w(C C# D D# E F F# G G# A A# B)
  enum scale: {maj: true, min: false}

  def key_scale
    "#{self.key}#{scale}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chords_controller.rb
class ChordsController < ApplicationController
  before_action :set_chord, only: [:show, :edit, :update, :destroy]

  # GET /chords
  def index
    @chords = Chord.all
  end

  # GET /chords/1
  def show
  end

  # GET /chords/new
  def new
    @chord = Chord.new
  end

  # GET /chords/1/edit
  def edit
  end

  # POST /chords
  def create
    @chord = Chord.new(chord_params)

    if @chord.save
      redirect_to @chord, notice: 'Chord was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /chords/1
  def update
    if @chord.update(chord_params)
      redirect_to @chord, notice: 'Chord was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /chords/1
  def destroy
    @chord.destroy
    redirect_to chords_url, notice: 'Chord was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chord
      @chord = Chord.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def chord_params
      params.require(:chord).permit(:name)
    end
end

app/controllers/composers_controller.rb
class ComposersController < ApplicationController
  before_action :set_composer, only: [:show, :edit, :update, :destroy]

  # GET /composers
  # GET /composers.json
  def index
    @composers = Composer.all
  end

  # GET /composers/1
  # GET /composers/1.json
  def show
  end

  # GET /composers/new
  def new
    @composer = Composer.new
  end

  # GET /composers/1/edit
  def edit
  end

  # POST /composers
  # POST /composers.json
  def create
    @composer = Composer.new(composer_params)

    respond_to do |format|
      if @composer.save
        format.html { redirect_to @composer, notice: 'Composer was successfully created.' }
        format.json { render :show, status: :created, location: @composer }
      else
        format.html { render :new }
        format.json { render json: @composer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /composers/1
  # PATCH/PUT /composers/1.json
  def update
    respond_to do |format|
      if @composer.update(composer_params)
        format.html { redirect_to @composer, notice: 'Composer was successfully updated.' }
        format.json { render :show, status: :ok, location: @composer }
      else
        format.html { render :edit }
        format.json { render json: @composer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /composers/1
  # DELETE /composers/1.json
  def destroy
    @composer.destroy
    respond_to do |format|
      format.html { redirect_to composers_url, notice: 'Composer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_composer
      @composer = Composer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def composer_params
      params.require(:composer).permit(:name, :created_by, :updated_by, :deleted_by, :deleted_at)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  def index
    @songs = Song.all
  end

  # GET /songs/1
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to @song, notice: 'Song was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /songs/1
  def update
    if @song.update(song_params)
      redirect_to @song, notice: 'Song was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /songs/1
  def destroy
    @song.destroy
    redirect_to songs_url, notice: 'Song was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def song_params
      params.require(:song).permit(:title, :composer_id, :tempo, :key, :scale)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/composers_helper.rb
module ComposersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/chords/_form.html.erb
<%- only_show ||= false -%>
<%= simple_form_for(@chord) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, disabled: only_show %>
  </div>

<%- unless only_show -%>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<%- end -%>
<% end %>

app/views/chords/edit.html.erb
<h1>Editing Chord</h1>

<%= render 'form' %>

<div class="text-center">
  <%= link_to 'Back', chords_path, class: "btn btn-default" %> |
  <%= link_to 'Show', @chord, class: "btn btn-info" %>
</div>

app/views/chords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chords</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chords.each do |chord| %>
      <tr>
        <td><%= chord.name %></td>
        <td class="text-center"><%= link_to 'Show', chord, class: 'btn btn-success' %></td>
        <td class="text-center"><%= link_to 'Edit', edit_chord_path(chord), class: 'btn btn-primary' %></td>
        <td class="text-center"><%= link_to 'Destroy', chord, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="text-center">
  <%= link_to 'New Chord', new_chord_path, class: "btn btn-info" %>
</div>

app/views/chords/new.html.erb
<h1>New Chord</h1>

<%= render 'form' %>

<div class="text-center">
  <%= link_to 'Back', chords_path, class: "btn btn-default" %>
</div>

app/views/chords/show.html.erb
<h1>Show Chord</h1>
<p id="notice"><%= notice %></p>

<%= render "form", only_show: true %>

<div class="text-center">
  <%= link_to 'Back', chords_path, class: 'btn btn-default' %> |
  <%= link_to 'Edit', edit_chord_path(@chord), class: 'btn btn-primary' %>
</div>

app/views/codes/_form.html.erb
<%= simple_form_for(@code) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/composers/_form.html.erb
<%- only_show ||= false -%>
<%= simple_form_for(@composer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, disabled: only_show %>
  </div>

<%- unless only_show -%>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<%- end -%>
<% end %>

app/views/composers/edit.html.erb
<h1>Editing Composer</h1>

<%= render 'form' %>

<div class="text-center">
  <%= link_to 'Back', composers_path , class: "btn btn-default"%> |
  <%= link_to 'Show', @composer, class: "btn btn-success" %>
</div>

app/views/composers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Composers</h1>

<div class="table-resposive">
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @composers.each do |composer| %>
      <tr>
        <td><%= composer.name %></td>
        <td><%= link_to 'Show', composer, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_composer_path(composer), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', composer, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<div class="text-center">
  <%= link_to 'New Composer', new_composer_path, class: "btn btn-info" %>
</div>

app/views/composers/new.html.erb
<h1>New Composer</h1>

<%= render 'form' %>

<%= link_to 'Back', composers_path, class: "btn btn-default" %>

app/views/composers/show.html.erb
<h1>Show Composer</h1>
<p id="notice"><%= notice %></p>

<%= render "form", only_show: true %>

<div class="text-center">
  <%= link_to 'Back', composers_path, class: "btn btn-default" %> |
  <%= link_to 'Edit', edit_composer_path(@composer), class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rachmaninov</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle navbar-toggle-always collapsed pull-left" data-toggle="offcanvas" data-target="#sidebar" aria-expanded="false" aria-controls="navbar" id="sidebar-toggle">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <button type="button" class="navbar-toggle collapsed pull-right" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle Search</span>
        <span class="glyphicon glyphicon-search"></span>
      </button>

      <a class="navbar-brand" href="/">Rachmaninov</a>

    </div>

    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav hidden-xs">
        <li><%= link_to 'songs', songs_path %></li>
        <li><%= link_to 'composers', composers_path %></li>
        <li><%= link_to 'chords', chords_path %></li>
      </ul>
      <form class="navbar-form navbar-right">
        <input class="form-control" placeholder="Search..." type="text">
      </form>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</div><!-- /.navbar -->

<div class="container-fluid">
<div class="col-xs-4 col-sm-3 sidebar-offcanvas row-offcanvas-left row-offcanvas" id="sidebar">
  <div class="nav-container">
    <h4 class="text-center">Global Navigation</h4>
    <ul class="list-group">
      <li><%= link_to 'songs', songs_path %></li>
      <li><%= link_to 'composers', composers_path %></li>
      <li><%= link_to 'chords', chords_path %></li>
    </ul>
 <% if @local_navigation -%>
    <h4 class="text-center">Local Navigation</h4>
    <div class="list-group">
      <%- @local_navigation.each do |id, text| %>
      <a href="#<%= id %>" class="list-group-item"><%= text %></a>
      <%- end -%>
    </div>
<% end -%>
  </div>
  <!--<div class="offCanvasTrick" data-toggle="offcanvas"></div>-->
</div>

<div class="inbody">

<div class="col-xs-12">
<%= yield %>

<footer>
<p class="text-right text-muted">Copyright &copy; swan_match</p>
</footer>

</div>
</div>

</div>
</body>
</html>

app/views/songs/_form.html.erb
<%- only_show ||= false -%>
<%= simple_form_for(@song) do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-sm-6">
      <%= f.input :title, disabled: only_show %>
    </div>
    <div class="col-sm-6">
      <%= f.association :composer, disabled: only_show %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4">
      <%= f.input :tempo, disabled: only_show  %>
    </div>
    <div class="col-sm-4">
      <%= f.input :key, include_blank: false, collection: Song.keys.keys, as: :select, disabled: only_show %>
    </div>
    <div class="col-sm-4">
      <%= f.input :scale, collection: Song.scales.keys, as: :radio_buttons, disabled: only_show %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= f.input :midi_file, as: :file, disabled: only_show %>
    </div>
  </div>

  <%- unless only_show -%>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
  <%- end -%>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<div class="text-center">
  <%= link_to 'Back', songs_path, class: "btn btn-default" %> |
  <%= link_to 'Show', @song, class: "btn btn-success" %>
</div>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Composer</th>
      <th>Tempo</th>
      <th>Key</th>
      <th>Scale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.composer.name %></td>
        <td><%= song.tempo %></td>
        <td><%= song.key %></td>
        <td><%= song.scale %></td>
        <td class="text-center"><%= link_to 'Show', song, class: "btn btn-success" %></td>
        <td class="text-center"><%= link_to 'Edit', edit_song_path(song), class: "btn btn-primary" %></td>
        <td class="text-center"><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="text-center">
  <%= link_to 'New Song', new_song_path, class: "btn btn-info" %>
</div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<div class="text-center">
  <%= link_to 'Back', songs_path, class: "btn btn-default" %>
</div>

app/views/songs/show.html.erb
<h1>Show Song</h1>
<p id="notice"><%= notice %></p>

<%= render "form", only_show: true %>

<div class="text-center">
  <%= link_to 'Back', songs_path, class: "btn btn-default" %> |
  <%= link_to 'Edit', edit_song_path(@song), class: "btn btn-primary" %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<%
require 'action_dispatch/routing/inspector'
all_routes = Rails.application.routes.routes
inspector = ActionDispatch::Routing::RoutesInspector.new(all_routes)
#(all_routes).format(ActionDispatch::Routing::ConsoleFormatter.new).split(/\n/)
#all_routes = Rails.application.routes.routes
#inspector = Rails::Application::RouteInspector.new
inspector.instance_values["routes"].reject{|r| r.parts.size != 1 || r.name.blank? || r.name.include?("new") || r.name.include?("rails") }.map(&:name).compact.each do |path|
%>

<p>
<%= link_to path, self.try("#{path}_path") %>
</p>
<%- end -%>